### ISSUE TITLE
혹시 yolov8을 어떻게 적용했는지 여쭤볼 수 있을까요??

### ISSUE THREAD

**Issue by WhiteSweetPotato** [Yurve/YOLOv8_Pose_android#1]
알려주시면 감사드리겠습니다!!

**Comment by Aloe-droid** [comment]
블로그로 글도 썼었는데 이 부분 보시면 될 듯 합니다
// yolov8 - pose
https://velog.io/@aloe/YOLOv8n-Pose-%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-1
https://velog.io/@aloe/YOLOv8-pose-%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-2
//참고하면 좋은 글 
https://velog.io/@aloe/FILLCENTER%EC%9D%98-%EB%B9%84%EB%B0%80

**Comment by WhiteSweetPotato** [comment]
정말 감사합니다!!!
