### ISSUE TITLE
How did the questioner convert the YOLO model to ONNX?

### ISSUE THREAD

**Issue by jungyin** [Yurve/YOLOv8_Pose_android#2]
I am trying to convert my YOLO model to ONNX and then to tflite, but the ONNX model generated during this process is exceptionally large. Can you please advise me on how to convert the ONNX model so that it is not too large? My yolo pose model has a size of 100mb after conversion

**Comment by Aloe-droid** [comment]
In general, converting to ONNX will increase the size. It depends on the size of your model (before converting to ONNX), but if your existing model is already large, you will end up with a large ONNX model. 

For example, if you download the yolov8x-seg model from the YOLOv8 GitHub, it's about 136 MB. If you convert it to an ONNX model, it's about 271.68 MB. 

The conversion code is shown below.
<Python code>
from ultralytics import YOLO

model = YOLO(model='yolov8n-pose.pt')
model.export(format="tflite")

**Comment by jungyin** [comment]
> In general, converting to ONNX will increase the size. It depends on the size of your model (before converting to ONNX), but if your existing model is already large, you will end up with a large ONNX model.
> 
> For example, if you download the yolov8x-seg model from the YOLOv8 GitHub, it's about 136 MB. If you convert it to an ONNX model, it's about 271.68 MB.
> 
> The conversion code is shown below. from ultralytics import YOLO
> 
> model = YOLO(model='yolov8n-pose.pt') model.export(format="tflite")

Okay, it seems possible. My colleague renamed the yolov8x level model to yolov8n, which resulted in the model I transferred being too large
